### ISSUE TITLE
Getting error "AttributeError: module 'socket' has no attribute 'TCP_KEEPIDLE'" when trying to run server

### ISSUE THREAD

**Issue by weakman54** [stolencatkarma/CataclysmLD#13]
Full traceback:
```
Traceback (most recent call last):
  File "server.py", line 1020, in <module>
    server.connect(ip, port)
  File "C:\dev\python37\CataclysmLD\Mastermind\_mm_server.py", line 142, in connect
    self._mm_make_connection(ip, port)
  File "C:\dev\python37\CataclysmLD\Mastermind\_mm_server.py", line 252, in _mm_make_connection
    socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, 1
AttributeError: module 'socket' has no attribute 'TCP_KEEPIDLE'
```

This seems to be an issue with the socket library as indicated by this other issue:
https://github.com/websocket-client/websocket-client/issues/75

Mastermind seems to be the culprit, since it's there that these settings are set:
```
def _mm_make_connection(self, ip, port):
    ...
    self._mm_unconnected_socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, 1)
```

**Comment by weakman54** [comment]
Commented the offending lines out of master mind, and can now start the server, though I have no idea what the consequences would be when those options are not set...

**Comment by stolencatkarma** [comment]
What OS are you on? What python version?
________________________________

**Comment by Melodeiro** [comment]
Same error, Windows 10, python 3.7.2. Commented out 251-259 lines from `Mastermind\_mm_server.py`, and it is started. Connection attempt seems fine, didn't tested it further

**Comment by stolencatkarma** [comment]
i believe we tracked this error down to different socket libraries on different OSes.

**Comment by alexeast99** [comment]
I'm getting this error as well using Python in MSYS2. I would love some help!

**Comment by stolencatkarma** [comment]
> I'm getting this error as well using Python in MSYS2. I would love some help!

it's an issue with how your system implements socket.h and far outside of the scope I can help you with. Sorry.

**Comment by KeithTt** [comment]
Encounter this error on MacOS...

**Comment by stolencatkarma** [comment]
MacOS must not support TCP_KEEPIDLE in the socket library. you can try
commenting it out. others had luck.

**Comment by martinv-github** [comment]
Just do this. Tested on Python 3.9
```
TCP_KEEPALIVE = 0x10
sock.setsockopt(socket.IPPROTO_TCP, TCP_KEEPALIVE, ...)
```
[see this for ref](https://github.com/apple/darwin-xnu/blob/main/bsd/netinet/tcp.h#L215C90-L215C90)
