### ISSUE TITLE
Proper installation and run instructions are needed

### ISSUE THREAD

**Issue by Aivean** [stolencatkarma/CataclysmLD#2]
Currently the only prerequisite seems to be `pygame`, but even still, for people unfamiliar with python who don't have pip installing it and running the game (or wysiwyg) may be cumbersome. 

Short term this can be solved by proving clear step-by-step instructions on how to install and run the game, such as:
1. install python (link)
2. install pip (link)
3. install pygame (howto)
4. run the game

In the future it's probably the best to have some kind of [setup script](https://docs.python.org/2/distutils/setupscript.html) that does all the dirty work.

**Comment by stolencatkarma** [comment]
I wrote up a little tidbit in the README.md but i think i'll leave this open because it could be better.

**Comment by stolencatkarma** [comment]
merged the request. closing this. i think it's good for now. thanks bud.
