### ISSUE TITLE
Use Cataclysm executable as base for server

### ISSUE THREAD

**Issue by aaferrari** [stolencatkarma/CataclysmLD#33]
What do you think about using the functions of the Cataclysm DDA executable for the server? I think that calling some functions through [ctypes](https://docs.python.org/3/library/ctypes.html) could benefit this project by not having to reimplement functionalities from scratch (at least in the short term). Here is an example that I made with one_in() function:
```
from ctypes import CDLL
# Change for the path of the executable, I suppose that in Windows it should work the same
cataclysm = CDLL("/usr/bin/cataclysm")
# Results
>>> cataclysm._Z6one_ini(100)
0
>>> cataclysm._Z6one_ini(15)
0
```
`one_in` can be used transparently since it accepts an integer as a parameter and returns 0 or 1 (at least if the parameter is less than 200), although with functions that handle custom data types (such as objects)  more work may be needed.
To know the functions that the executable exports you can use [DLL Export Viewer](https://www.nirsoft.net/utils/dll_export_viewer.html) in Windows or the following command in Linux:
```
nm -D /path/to/the/cataclysm/bin | grep -E "[a-f0-9]+ T"
```
If you consider the idea viable, in the long run you could create a library that only contains the necessary functions (although at the moment you could put the path of the executable in server.cfg).

**Comment by stolencatkarma** [comment]
I'm staying away from c and ctypes altogether. I'm also trying to keep
things beginner programmer friendly.

I'm an amateur programmer myself and keeping everything in one language and
one object notation (JSON) is imperative.

I do really appreciate the feedback and suggestions though. Sorry for the
late reply.
