### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'AF_INET'

### ISSUE THREAD

**Issue by janus109** [stolencatkarma/CataclysmLD#35]
My python script works when I run it manually in Spyder. Nowadays I use a bat file as automated and scheduled. Previously it worked but since I format my computer it stopped to work. 
It says : AttributeError: module 'socket' has no attribute 'AF_INET'

see pic. Not sure if that work?

![image](https://user-images.githubusercontent.com/67426237/85736691-fcf3b580-b6fe-11ea-9d84-0bb3ea619978.png)

**Comment by stolencatkarma** [comment]
this is an issue with the socket subsystem on some systems. I know win8.1 has this issue as well. There is nothing i can do.
