### ISSUE TITLE
Project structure reorganization

### ISSUE THREAD

**Issue by Aivean** [stolencatkarma/CataclysmLD#5]
As project is growing it's sensible to organize the codebase into scalable directory structure.

I don't have a strong opinion on how exactly to structure the code, but I guess anything is better than no structure. Perhaps we can start with something as simple as:

     ./src/
     ./test/
     ./asset/

Or maybe separate subtrees for different subprojects:

      ./common
          ./src/
          ./test/
          ./asset/
      ./wysiswg
          ./src/
          ./test/
          ./asset/
      ./client
          ./src/
          ./test/
          ./asset/
      ./server
          ./src/
          ./test/
          ./asset/

[Stackoverflow link for inspiration](https://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application)

**Comment by stolencatkarma** [comment]
personally i'd like to leave the client, server, and editors in the main directory and move all the supporting files to subfolders.

**Comment by Aivean** [comment]
That will work too. 
I'd do that sooner rather than later. Keeping codebase clean and organized helps with readability, which is important, especially if you want other people to contribute.

**Comment by stolencatkarma** [comment]
i pushed a commit for this. closing.
