### ISSUE TITLE
Error on connecting with a fresh server

### ISSUE THREAD

**Issue by schlegan** [stolencatkarma/CataclysmLD#6]
I download the current build, commit 84f1f08, and installed everything.
After starting the server for the first time and connecting, the server displayed this error:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "..\src\worldmap.py", line 156, in get_tile_by_position
    for tile in self.WORLDMAP[x_count][y_count][z].tiles:
KeyError: 7

The actual error was a bit longer, but I cut it down to what I believe are the essentials.
All required libraries seem to be installed. The player window shows a bunch of dirt tiles if that helps.

**Comment by stolencatkarma** [comment]
this was fixed as of latest patch. thanks for the feedback.
